---
apiVersion: v1
kind: Namespace
metadata:
  name: meow-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-garfield
  namespace: meow-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: meow-world
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80